spring:
  application:
    name: github-connector-service

integration:
  github:
    url: https://api.github.com

logging:
  level:
    io.netty: ERROR

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      url: /static/swagger.yaml
