openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8081
    description: Generated server url
paths:
  /api/v1/users/{username}/repositories:
    get:
      tags:
        - git-hub-controller
      operationId: getRepositories
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RepositoryData'
components:
  schemas:
    BranchData:
      type: object
      properties:
        name:
          type: string
        commit:
          $ref: '#/components/schemas/CommitData'
    CommitData:
      type: object
      properties:
        sha:
          type: string
    RepositoryData:
      type: object
      properties:
        name:
          type: string
        owner:
          type: string
        branches:
          type: array
          items:
            $ref: '#/components/schemas/BranchData'
